name: Build and Deploy React App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: [self-hosted, linux, arm64, raspberrypi]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.9.0'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
      
      - name: Build React app
        run: npm run build
        
      - name: Setup Nginx
        run: |
          sudo apt-get update
          sudo apt-get install -y nginx
          
      - name: Configure Nginx
        run: |
          sudo tee /etc/nginx/sites-available/react-app > /dev/null << EOT
          server {
              listen 80;
              server_name localhost;
              
              root /var/www/react-app;
              index index.html;
              
              location / {
                  try_files \$uri /index.html;
              }
          }
          EOT
          sudo ln -sf /etc/nginx/sites-available/react-app /etc/nginx/sites-enabled/
          sudo rm -f /etc/nginx/sites-enabled/default
          
      - name: Deploy to Nginx
        run: |
          sudo mkdir -p /var/www/react-app
          sudo rm -rf /var/www/react-app/*
          sudo cp -r dist/* /var/www/react-app/
          sudo chown -R www-data:www-data /var/www/react-app
          sudo chmod -R 755 /var/www/react-app
          
      - name: Restart Nginx
        run: sudo systemctl restart nginx